---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.8
    run_list:
    - recipe[yum]
  - name: centos-7.2
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[sssd-test::jumpcloud]
      - recipe[sssd::default]
